services:
  db:
    build: ./db
    container_name: postgres-db
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dictionary
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend